[package]
name = "knolo-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Knolo agent runtime."

repository = "https://github.com/knolo-ai/knolo-agents"
homepage = "https://github.com/knolo-ai/knolo-agents"
readme = "../../README.md"
keywords = ["knolo", "agents", "ai"]
categories = ["development-tools"]

[dependencies]
knolo-agent-core.workspace = true
serde.workspace = true
serde_json.workspace = true
